### ISSUE TITLE
和原论文的实现有区别

### ISSUE THREAD

**Issue by renmada** [CuberrChen/AdvSemiSeg-Paddle#1]
1. 这里用resnetvd
2. 加了deeplab的head
以上是我看原repo代码的理解，不一定对。

我也尝试复现这篇，训练的时候发现loss的变化和pytorch的不一致就放弃了；跑了一下aistudio的项目，loss的变化和pytorch的也不一致，不过seg_loss是下降的，我的seg_loss反复横跳。

**Comment by CuberrChen** [comment]
原文项目的resnet和deeplab的头是写在一起，为“Res-Deeplab”。这个没什么问题。对于loss，原文项目我没输出过loss的曲线，所有不知道是怎么样的。项目是从原文的代码一一对应改过来的，应该问题不大吧hh。有兴趣的话，您可以帮忙指出一下哪里代码不对吗？

**Comment by renmada** [comment]
- 我没做过cv方向的，所以对原repo的代码理解纯属个人理解，不一定对；只是在看完本repo复现后，发现有不一样的地方，有点疑惑
- 原repo的模型虽然Res_Deeplab，但是貌似没有与本repo类似的deeplab代码

**Comment by CuberrChen** [comment]
实际上是一样的...这里的Deeplab Head实际上只是封装了一个ASPP模块，其他啥也没做。而ASPP模块就是Deeplab的核心模块，对应到原项目代码的话，就是Classifier_Module...也就是Resnet之后的模块。嗯嗯，可以多交流.
